In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[['Jateng' 21.0 72000.0]
 ['Jabar' 22.0 48000.0]
 ['Jatim' 22.0 54000.0]
 ['Jabar' 24.0 61000.0]
 ['Jateng' 21.0 nan]
 ['Jatim' 24.0 58000.0]
 ['Jateng' nan 52000.0]
 ['Jabar' 25.0 79000.0]
 ['Jatim' 23.0 83000.0]
 ['Jateng' 21.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
print(x)

[['Jateng' 21.0 72000.0]
 ['Jabar' 22.0 48000.0]
 ['Jatim' 22.0 54000.0]
 ['Jabar' 24.0 61000.0]
 ['Jateng' 21.0 63777.77777777778]
 ['Jatim' 24.0 58000.0]
 ['Jateng' 22.555555555555557 52000.0]
 ['Jabar' 25.0 79000.0]
 ['Jatim' 23.0 83000.0]
 ['Jateng' 21.0 67000.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[0.0 1.0 0.0 21.0 72000.0]
 [1.0 0.0 0.0 22.0 48000.0]
 [0.0 0.0 1.0 22.0 54000.0]
 [1.0 0.0 0.0 24.0 61000.0]
 [0.0 1.0 0.0 21.0 63777.77777777778]
 [0.0 0.0 1.0 24.0 58000.0]
 [0.0 1.0 0.0 22.555555555555557 52000.0]
 [1.0 0.0 0.0 25.0 79000.0]
 [0.0 0.0 1.0 23.0 83000.0]
 [0.0 1.0 0.0 21.0 67000.0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [ ]:
print(x_train)

[[0.0 1.0 0.0 22.555555555555557 52000.0]
 [0.0 1.0 0.0 21.0 63777.77777777778]
 [0.0 1.0 0.0 21.0 72000.0]
 [1.0 0.0 0.0 24.0 61000.0]
 [1.0 0.0 0.0 22.0 48000.0]
 [1.0 0.0 0.0 25.0 79000.0]
 [0.0 0.0 1.0 23.0 83000.0]
 [0.0 0.0 1.0 24.0 58000.0]]


In [ ]:
print(x_test)

[[0.0 0.0 1.0 22.0 54000.0]
 [0.0 1.0 0.0 21.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.fit_transform(x_test[:, 3:])

In [ ]:
print(x_train)

[[0.0 1.0 0.0 -0.1931249374124486 -1.0781259408412425]
 [0.0 1.0 0.0 -1.3315456211068972 -0.07013167641635372]
 [0.0 1.0 0.0 -1.3315456211068972 0.633562432710455]
 [1.0 0.0 0.0 0.8639799831609657 -0.30786617274297867]
 [1.0 0.0 0.0 -0.5997037530176095 -1.420463615551582]
 [1.0 0.0 0.0 1.5958218512502533 1.232653363453549]
 [0.0 0.0 1.0 0.13213811507167808 1.5749910381638885]
 [0.0 0.0 1.0 0.8639799831609657 -0.5646194287757332]]


In [ ]:
print(x_test)

[[0.0 0.0 1.0 1.0 -1.0]
 [0.0 1.0 0.0 -1.0 1.0]]
